// <auto-generated />
using MiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MiApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiApi.Cervezas", b =>
            {
                b.Property<int>("IdCerveza") // Cambiado desde "id_cerveza"
                    .ValueGeneratedNever() // No es autoincremental según tu definición
                    .HasColumnType("NUMBER"); // Cambiado a NUMBER (sin especificar longitud porque es PRIMARY KEY)

                b.Property<decimal>("Graduacion")
                    .HasPrecision(5, 2) // Ajusta la precisión de NUMBER(5, 2)
                    .HasColumnType("NUMBER(5,2)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(100) // Cambiado para coincidir con VARCHAR2(100)
                    .HasColumnType("NVARCHAR2(100)");

                b.Property<string>("Pais")
                    .IsRequired()
                    .HasMaxLength(100) // Cambiado para coincidir con VARCHAR2(100)
                    .HasColumnType("NVARCHAR2(100)");

                b.HasKey("IdCerveza"); // Definido como clave primaria

                b.ToTable("CERVEZAS", (string)null); // Tabla CERVEZAS en la base de datos
            });
#pragma warning restore 612, 618
        }
    }
}
